services:
  postgres:
    image: postgres:16
    container_name: maker-music-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Krazynn17
      - POSTGRES_DB=maker_music_t1
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: